### ISSUE TITLE
2.8.0 cli 脚手架新建项目的 eslintrc，vscode 内未提示

### ISSUE THREAD

**Issue by wytheglobal** [mpx-ecology/eslint-plugin-mpx#14]
**清单**

- [ ] 我已尝试重新启动我的 IDE，但问题仍然存在。
- [ ] 我已阅读 [FAQ](https://eslint.mpxjs.org/user-guide/#faq)，我的问题未列出。

**告诉我们您的环境**

- **ESLint 版本：**
- **eslint-plugin-mpx 版本：**
- **节点版本：**
- **操作系统：**

**请显示您的完整配置：**

```json5

```

**你做了什么？**

```vue

```

**您期望会发生什么？**

**实际发生了什么？**

**重现此问题的存储库**

const { userConf } = require('./config/index')

const eslintConf = {
  root: true,
  parser: '@babel/eslint-parser',
  parserOptions: {
    sourceType: 'module'
  },
  extends: 'standard',
  settings: {
    // consider .html and .mpx files as HTML
    'html/html-extensions': ['.html', '.mpx']
  },
  plugins: [
    'html'
  ],
  globals: {
    wx: 'readonly',
    getApp: 'readonly',
    App: 'readonly',
    Page: 'readonly',
    Component: 'readonly',
    __mpx_mode__: 'readonly',
    __mpx_env__: 'readonly',
    requirePlugin: 'readonly'
  },
  rules: {
    camelcase: ['error', { allow: ['__mpx_mode__', '__mpx_env__'] }]
  }
}
if (userConf.tsSupport) {
  eslintConf.overrides = [
    {
      files: ['**/*.ts', '**/*.mpx'],
      parser: '@typescript-eslint/parser',
      extends: [
        'standard',
        'plugin:@typescript-eslint/eslint-recommended',
        'plugin:@typescript-eslint/recommended',
      ],
      plugins: ['@typescript-eslint'],
    },
  ]
}

module.exports = eslintConf

**Comment by pagnkelly** [comment]
你这是老配置，可以按照此仓库readme配置，或者按照 https://github.com/mpx-ecology/eslint-config/ 此仓库配置
